#ifndef OPERATIONTEST_GLOBAL_H
#define OPERATIONTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPERATIONTEST_LIBRARY)
#  define OPERATIONTEST_EXPORT Q_DECL_EXPORT
#else
#  define OPERATIONTEST_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERATIONTEST_GLOBAL_H
