#ifndef ILWS3CONNECTORTEST_GLOBAL_H
#define ILWS3CONNECTORTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ILWS3CONNECTORTEST_LIBRARY)
#  define ILWS3CONNECTORTESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ILWS3CONNECTORTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ILWS3CONNECTORTEST_GLOBAL_H
